server:
  port: 8080
  servlet:
    context-path: /api
spring:
  mvc:
    versioning:
      strategy: header
  application:
    name: wacdo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wacdov2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      test-while-idle: true
  security:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update   # update | validate | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

# Logger SQL lisible
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # voir les valeurs bind√©es (super utile)


